[versions]
shadow = "9.4.3"
resourcefactory = "1.3.1"

paperApi = "1.21.11-R0.1-SNAPSHOT"
lombok = "1.18.46"
protocollib = "5.4.0"

[libraries]
paperApi = { module = "io.papermc.paper:paper-api", version.ref = "paperApi" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
protocollib = { module = "net.dmulloy2:ProtocolLib", version.ref = "protocollib" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resourcefactory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resourcefactory" }
